name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            cd ~/bilecik
            git pull
            docker compose --profile bot up --build -d
